In [1]:
import numpy as np

In [3]:
a = np.arange(8)
bins = np.arange(3,6)
print(a)
print(bins)

bindex = np.digitize(a, bins=bins, right=True)
print(print(bindex))
digitized = a[bins[bindex]]


[0 1 2 3 4 5 6 7]
[3 4 5]
[0 0 0 1 2 3 3 3]
None


IndexError: index 3 is out of bounds for axis 0 with size 3